[relaychain]
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  ws_port = 9900
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
    ws_port = 9901
  extra_args = [ "-lparachain=debug" ]

[[parachains]]
id = 1000
add_to_genesis = true
cumulus_based = true
chain = "coretime-rococo-local"
  [[parachains.collators]]
  name = "westmint-collator01"
  command = "polkadot-parachain"
  ws_port = 9944
  args = ["--log=xcm=trace,pallet-assets=trace"]

  [[parachains.collators]]
  name = "westmint-collator02"
  command = "polkadot-parachain"
  ws_port = 9911
  args = ["--log=xcm=trace,pallet-assets=trace"]